### PR TITLE
Subscribe layout change, not just get context

### PR DESCRIPTION
**Pull request by jhen0409**
Related to https://github.com/machadogj/react-native-layout-tester/issues/4#issuecomment-229129050.

### CODE REVIEW

**Comment by jhen0409** [comment]
Also I change layoutTesterState to getLayoutTesterState function, because HMR will lead it get the old state.

**Comment by jhen0409** [comment]
@machadogj what do you think about this PR? Currently I need use my fork to get work.

**Comment by machadogj** [comment]
Looks good on paper, I didn't have a chance to test it. Could you please update the docs (readme file) with a sample?
I want to explore at some point defining the styles as a static prop and allowing the use of functions that could calculate properties based on the props and context. As soon as I get a little bit of time.

**Comment by jhen0409** [comment]
It looks not need to update doc, it just fixed `shouldComponentUpdate` for context problem.

The originally problem can be reproduced with following example, you can try it directly on the old version:

``` js
const Comp = getLayout(layout => layout)(props => {
  console.log(props);
  return <View></View>;
});

class Wrap extends Component {

  shouldComponentUpdate() {
    return false;  // layout-tester@1.0.4: it causes Comp cannot get updated context
  }

  render() {
    return (
      <Comp />
    );
  }
}

const App = props =>
  <LayoutTester>
    <Wrap />
  </LayoutTester>;
```

**Comment by machadogj** [comment]
Excellenet then!

**Pull request merged**
